# version: '3.8'

# services:
#   graphql-server:
#     build: .
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/usr/src/app
#     environment:
#       - FLASK_ENV=development
#     command: python app.py
version: '3.8'

services:
  graphql-server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - D:/Granting-database:/data  # Mount the GRANTING-DATABASE directory into the container
    environment:
      - FLASK_ENV=development
    command: python app.py

